<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         DB::table('users')->insert([
            ['first_name' => "Sawankumar",
            'last_name' => "Naik",
            'email' => 'naiksa1@gmail.com',
            'password' => bcrypt('naik123!'),
            'status' => '1',
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'role_id' => 1],
            ['first_name' => "Team1",
            'last_name' => "Account",
            'email' => 'team1@ts.com',
            'password' => bcrypt('demopassword'),
            'status' => '1',
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'role_id' => 4],
            ['first_name' => "Team2",
            'last_name' => "Account",
            'email' => 'team2@ts.com',
            'password' => bcrypt('demopassword'),
            'status' => '1',
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'role_id' => 4],
            ['first_name' => "Team3",
            'last_name' => "Account",
            'email' => 'team3@gmail.com',
            'password' => bcrypt('demopassword'),
            'status' => '1',
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'role_id' => 4],
            ['first_name' => "Team4",
            'last_name' => "Account",
            'email' => 'team4@ts.com',
            'password' => bcrypt('demopassword'),
            'status' => '1',
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'role_id' => 4],
            ['first_name' => "Team5",
            'last_name' => "Account",
            'email' => 'team5@ts.com',
            'password' => bcrypt('demopassword'),
            'status' => '1',
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'role_id' => 4],
            ['first_name' => "Team6",
            'last_name' => "Account",
            'email' => 'team6@gmail.com',
            'password' => bcrypt('demopassword'),
            'status' => '1',
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'role_id' => 4],
            ['first_name' => "Team7",
            'last_name' => "Account",
            'email' => 'team7@ts.com',
            'password' => bcrypt('demopassword'),
            'status' => '1',
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'role_id' => 4],
            ['first_name' => "Team8",
            'last_name' => "Account",
            'email' => 'team8@ts.com',
            'password' => bcrypt('demopassword'),
            'status' => '1',
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'role_id' => 4],
            ['first_name' => "Team9",
            'last_name' => "Account",
            'email' => 'team9@gmail.com',
            'password' => bcrypt('demopassword'),
            'status' => '1',
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'role_id' => 4],
            ['first_name' => "Judge1",
            'last_name' => "Account",
            'email' => 'judge1@ts.com',
            'status' => '1',
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'password' => bcrypt('judge123!'),
            'role_id' => 2],
            ['first_name' => "Judge2",
            'last_name' => "Account",
            'email' => 'judge2@ts.com',
            'status' => '1',
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
            'password' => bcrypt('judge123!'),
            'role_id' => 2],
        ]);
    }
}
